
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Teja@1234
      POSTGRES_DB: postgres
    networks:
      - mynetwork

  web:
    build: .
    command: gunicorn your_project_name.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
